#!/bin/bash

# Get the workspace name from the argument
workspace_name="$1"

# Get workspace details
output="$(swaymsg -t get_tree | jq -r --arg workspace_name "$workspace_name" 'recurse(.nodes[]?) | select(.name==$workspace_name).nodes[].app_id')"
number="$(swaymsg -t get_tree | jq -r --arg workspace_name "$workspace_name" 'recurse(.nodes[]?) | select(.name==$workspace_name).nodes | length')"

if [ "$number" -gt 0 ]; then
    text="缾 $number"
else
    text=""
fi

# Format the tooltip
output="$(echo "$output" | sed -r 's/[&]+/and/g')" # Replace unprintable & character with the word 'and'
tooltip="缾 $workspace_name\n\n"
tooltip+="$(echo "$output" | sed -z 's/\n/\\n/g')"
tooltip=${tooltip::-2}

echo "{\"text\":\"$text\", \"tooltip\":\"$tooltip\"}"
exit 0
