#!/bin/bash

# Define the base filename
filename=~/Pictures/scrn-$(date +"%Y-%m-%d-%H:%M:%S").png

# Function to capture full screen
function capture_full() {
    grim - | tee "$filename" | wl-copy
    notify-send " Full screenshot taken" -t 250
}

# Function to capture a selected area
function capture_area() {
    grim -g "$(slurp)" - | tee "$filename" | wl-copy
    notify-send " Area screenshot taken" -t 250
}

# Check for user input to decide the mode
case "$1" in
    full)
        capture_full
        ;;
    area)
        capture_area
        ;;
    *)
        echo "Invalid option. Use 'full' or 'area'."
        ;;
esac
