#!/bin/bash

# Screen recording management script for Hyprland, supporting start, select-area, and stop functionalities.

#!/bin/bash

case "$1" in
    start)
        notify-send -u critical " Screen Recording Started" -t 0
        wf-recorder -a -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused == true).name') -f ~/Videos/scrn-$(date +'%Y-%m-%d-%H:%M:%S').mp4 &> /dev/null

        ;;
    select)
        notify-send -u critical " Screen Recording Started" -t 0
        wf-recorder -a -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused == true).name') -g "$(slurp)" -f ~/Videos/scrn-$(date +'%Y-%m-%d-%H:%M:%S').mp4 &> /dev/null
        ;;
    stop)
        pkill -SIGINT wf-recorder
        notify-send -u low " Screen Recording Stopped" -t 0
        ;;
    *)
        echo "Invalid option: $1"
        echo "Usage: $0 {start|select|stop}"
        exit 1
        ;;
esac
