#!/bin/bash

case "$1" in
    forward)
        # Simulate pressing and releasing Mouse Button 9 (forward)
        ydotool click 0x05
        ;;
    backward)
        # Simulate pressing and releasing Mouse Button 8 (backward)
        ydotool click 0x06
        ;;
esac
