#!/bin/bash

case "$1" in
    forward)
        # Simulate pressing Alt + Right arrow key
        wtype -M alt -P right -m alt -p right
        ;;
    backward)
        # Simulate pressing Alt + Left arrow key
        wtype -M alt -P left -m alt -p left
        ;;
esac
