#!/bin/bash

SCRIPTNAME=$(basename $0)
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

download_from_url() {
    local url=$1
    local output_dir="~/Music/Recent" # Define the download directory

    # Define each flag individually
    local downloader="--downloader aria2c"
    local user_agent="--user-agent 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/5.0)'"
    local other_flags="--restrict-filenames --windows-filenames --concurrent-fragments 4 --no-mtime --geo-bypass --sleep-requests 2.59 --min-sleep-interval 1.10 --sleep-interval 3.59 --max-sleep-interval 4.59 --extract-audio --audio-format mp3 --output '$output_dir/%(title)s.%(ext)s'"

    # Combine all flags
    local combined_flags="$downloader $user_agent $other_flags"

    # Determine the source from the URL
    if [[ $url =~ soundcloud.com|youtube.com|youtu.be ]]; then
        eval yt-dlp -f bestaudio --embed-thumbnail --add-metadata $combined_flags "'$url'"
    else
        notify-send "Download Error" "Unsupported URL."
        return 1
    fi

    # Check for download success
    if [ $? -eq 0 ]; then
        notify-send "Download Complete" "Your MP3 track has been downloaded to $output_dir."
    else
        notify-send "Download Error" "Download was blocked or failed."
    fi
}

if [[ -n $DM ]]; then
    echo -e "\e[33mEnter URL (SoundCloud/YouTube):\e[0m"
    read url
    download_from_url "$url"
    exit
fi

# Launch Alacritty with the size we want and re-enter this script
DM=true $SHELL -c "alacritty \
    -o window.dimensions.columns=50 \
    -o window.dimensions.lines=3 \
    -o font.size=16.0 \
    -o window.padding.x=20 \
    -o window.padding.y=20 \
    --title 'music-download' \
    -e $SCRIPTPATH/$SCRIPTNAME"&
