#!/bin/bash

RESP=$(cat <<EOF | fzf
﫼Logout
⏾ Sleep
ﰇ Reboot
襤Shutdown
EOF
);

case "$RESP" in
	"﫼Logout")
		swaymsg exit
		;;
	"⏾ Sleep")
		systemctl suspend
		;;
	"ﰇ Reboot")
		systemctl reboot
		;;
	"襤Shutdown")
		systemctl poweroff
		;;
	*)
		exit 1
esac
