#!/bin/bash

# Check for valid usage
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {up|down}"
    exit 1
fi

# Define display devices
display1="sysfs/backlight/intel_backlight"
display2="sysfs/backlight/card1-eDP-2-backlight"

# Assign variables based on input
action=$1
amount=5  # default amount for up/down

# Execute light command based on action for each device
if [[ "$action" == "up" ]]; then
    light -A "$amount" -s "$display1"
    light -A "$amount" -s "$display2"
    notify-send "☀️ Brightness up" "$(light -G)" -t 250
elif [[ "$action" == "down" ]]; then
    light -U "$amount" -s "$display1"
    light -U "$amount" -s "$display2"
    notify-send "🔅 Brightness down" "$(light -G)" -t 250
fi
