#!/bin/sh

case "$@" in
    forward )
        scrollmsg seat seat0 cursor press BTN_EXTRA
        scrollmsg seat seat0 cursor release BTN_EXTRA
        ;;
    backward )
        scrollmsg seat seat0 cursor press BTN_SIDE
        scrollmsg seat seat0 cursor release BTN_SIDE
        ;;
    pgup)
        wtype -M ctrl -P tab -p tab -m ctrl
        ;;
    pgdn )
        wtype -M ctrl -M shift -P tab -p tab -m shift -m ctrl
        ;;
esac
