#!/bin/bash

markdown_dir="~/.config/sway/scripts/shortcuts"

# Create an associative array to map display names to file names
declare -A file_map=(
    ["nvim"]="nvim.md"
    ["sway"]="sway.md"
    ["terminal"]="terminal.md"
    ["vim"]="vim.md"
    ["fish"]="fish.md"
    ["ncmpcpp"]="ncmpcpp.md"

)

# Use fzf for selection with customized options
selection=$(printf "%s\n" "${!file_map[@]}" | fzf --reverse --header "Shortcut Menu")

# Check if a selection was made
if [ -n "$selection" ]; then
    file="$markdown_dir/${file_map[$selection]}"

    # Check if the file exists and pass it to glow
    if [ -f "$file" ]; then
        glow -p "$file"
    else
        echo "File not found: $file"
    fi
else
    echo "No selection made."
fi

