#!/bin/sh

case "$@" in
    forward )
        swaymsg seat seat0 cursor press BTN_EXTRA
        swaymsg seat seat0 cursor release BTN_EXTRA
        ;;
    backward )
        swaymsg seat seat0 cursor press BTN_SIDE
        swaymsg seat seat0 cursor release BTN_SIDE
        ;;
    pgup)
        wtype -M ctrl -P tab -p tab -m ctrl
        ;;
    pgdn )
        wtype -M ctrl -M shift -P tab -p tab -m shift -m ctrl
        ;;
esac
