#!/bin/bash

# This script uses swappy for screenshot annotation with options for full or area captures based on a flag.

# Check the argument for capture type
if [ "$1" == "full" ]; then
    grim - | swappy -f -
elif [ "$1" == "area" ]; then
    grim -g "$(slurp)" - | swappy -f -
else
    echo "Invalid command: $1. Use 'full' or 'area'."
    exit 1
fi
